# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dad1578f760abf286f54d185a6daad87c77dedc292c00c553eec77d4d98b915c95b9a81c3c1d34f61badc39cf05c639bd3427946e19eff5da27e1197b3b6f81

test:
  secret_key_base: 1ecffbd7e7e602f90918a5d2a5504e82ca5bc80a0bd7996ef8d50c8a65bce648dd1e25fa377aab8ebec0e064d2551271e6bc2009d7f92a2cd0927ce77f6cc1fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
